## 

SPECIES = ['pigs', 'chickens', 'carp', 'octopuses', 'bees', 'salmon', 'crayfish', 'shrimp',  'crabs', 'bsf', 'silkworms']

species_in_category_dict = {'wild vertebrates': ['all vertebrates'], 
                            'farmed fishes': ['262 fish species'], 
                            'farmed aquatic invertebrates': ['shrimp', 'crayfish, crabs, lobsters'],
                            'farmed land invertebrates': ['silkworms', 'crickets', 'cochineals', 'black soldier flies', 'mealworms'],
                            'farmed chickens': ['chickens'],
                            'farmed animals': ['fish', 'shrimp', 'crayfish, lobsters, crabs', 
                                               'silkworms', 'crickets', 'cochineals', 'black soldier flies', 'mealworms', 
                                               'chickens', 'cows', 'pigs', 'amphibians and reptiles', 'rabbits', 'fur animals',
                                               'animals for foie gras'],
                            'farmed cows': ['cows'],
                            'farmed pigs': ['pigs'],
                            'farmed rabbits': ['rabbits'],
                            'farmed animals for fur': ['mink, foxes, raccoon dogs, rabbits, chinchillas'],
                            'farmed animals for foie gras': ['ducks, geese'],
                            'animals in labs': ['rabbits, mice, dogs, monkeys'], 
                            'companion animals': ['dogs, cats'],
                            'working animals': ['horses, donkeys, mules, dogs'],
                            'animals in entertainment': ['8600 species in zoos/aquariums']}

proxy_species_and_weights = {'all vertebrates': {'carp': 0.5, 'salmon': 0.5},
                             '262 fish species': {'carp': 0.5, 'salmon': 0.5},
                             'shrimp': {'shrimp': 1},
                            'crayfish, crabs, lobsters': {'crayfish': 0.5, 'crabs': 0.5},
                            'silkworms': {'silkworms': 1},
                            'crickets': {'black soldier flies': 1},
                            'cochineals': {'silkworms': 1},
                            'black soldier flies': {'black soldier flies': 1},
                            'mealworms': {'silkworms': 1},
                            'chickens': {'chickens': 1},
                            'fish': {'carp': 0.5, 'salmon': 0.5},
                            'pigs': {'pigs': 1},
                            'amphibians and reptiles': {'chickens': 0.5, 'carp': 0.25, 'salmon':0.25},
                            'animals for foie gras': {'chickens': 1},
                            'rabbits': {'pigs': 1},
                            'cows': {'pigs': 1},
                            'mink, foxes, raccoon dogs, rabbits, chinchillas': {'pigs': 1},
                            'rabbits, mice, dogs, monkeys': {'pigs': 1},
                            'ducks, geese': {'chickens': 1},
                            'dogs, cats': {'pigs': 1},
                            'horses, donkeys, mules, dogs': {'pigs': 1},
                            '8600 species in zoos/aquariums': {'pigs': 1/3, 'chickens': 1/3, 'carp': 1/6, 'salmon': 1/6}}

